services:
  db:
    container_name: chat_app_db
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - chat-app
  redis:
    container_name: chat_app_redis
    image: redis:7.4.2-alpine
    restart: always
    env_file:
      - .env
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - chat-app

networks:
  chat-app:

volumes:
  db-data:
    driver_opts:
      type: nfs
      o: bind
      device: /home/wqr/chat-app/db-data

  redis-data:
    driver_opts:
      type: nfs
      o: bind
      device: /home/wqr/chat-app/redis-data
# FOR LATER WHEN BACKEND WILL BE IN DOCKER
# networks:
#   chat-app:
